puts "Peter Smith"
puts "Peter Smith"
puts "Peter Smith"
puts "Peter Smith"
puts "Peter Smith"
puts "Peter Smith"
puts "Peter Smith"
puts "Peter Smith"
puts "Peter Smith"
puts "Peter Smith"
puts "Peter Smith"
puts "Peter Smith"
puts "Peter Smith"
puts "Peter Smith"
puts "Peter Smith"
puts "Peter Smith"
puts "Peter Smith"
puts "Peter Smith"
puts "Peter Smith"
puts "Peter Smith"
puts "Peter Smith"
puts "Peter Smith"
puts "Peter Smith"
puts "Peter Smith"

print "Overall we have "
print 24
puts " great students"